### ISSUE TITLE
usage of umlauts results in corrupted user

### ISSUE THREAD

**Issue by MB175** [nitnelave/lldap#123] opened 2022-03-01 20:33 UTC
usage of umlauts results in corrupted user
<img width="1038" alt="Bildschirmfoto_2022-03-01_um_21 30 15" src="https://user-images.githubusercontent.com/57674787/156244476-b437a49c-1b01-48ef-bdec-9c92ecc1e7c1.png">
<img width="1037" alt="Bildschirmfoto_2022-03-01_um_21 29 54" src="https://user-images.githubusercontent.com/57674787/156244480-a929899d-c7e6-4999-adb8-275ef2fb41be.png">

**Comment by nitnelave** [comment] 2022-03-25 11:40
Hey, just FYI, I'm working with sea-query on a PR(https://github.com/SeaQL/sea-query/pull/275), and then with https://github.com/nitnelave/lldap/pull/127 we'll be free of dependency injections (or pesky umlaut issues). Then you can call your users O'Brïân if you want without issues.

**Comment by nitnelave** [comment] 2022-03-26 17:24
I'll just mark this as duplicate of #104 , since it's the same basic issue.

**Closed by nitnelave** 2022-03-26 17:24 UTC
